Add Export Macro for DLL Generation
teekae/blinkstickcpp pull request #2
Opened 2019-10-15 13:57 UTC by DeveloperPaul123

See #1

2019-10-31 10:38 UTC, teekae commented
Thanks for this PR, will try and test it soon

2019-12-18 21:19 UTC, teekae requested changes
Apologies for delay in looking at this.

Just suggested a small change to keep the headers consistent

2019-12-18 21:19 UTC, teekae commented on blinkstickcpp/CMakeLists.txt
> +generate_export_header(blinkstickcpp)
```suggestion
generate_export_header(blinkstickcpp EXPORT_FILE_NAME blinkstick/export.hpp)
```

2019-12-18 21:19 UTC, teekae commented on blinkstickcpp/CMakeLists.txt
> +            ${PROJECT_BINARY_DIR}/blinkstickcpp_export.h
```suggestion
            ${PROJECT_BINARY_DIR}/blinkstick/export.hpp
```

2019-12-18 21:19 UTC, teekae commented on blinkstickcpp/include/blinkstick/blinkstick.hpp
> +#include <blinkstickcpp_export.h>
```suggestion
#include <blinkstick/export.hpp>
```

2019-12-18 21:19 UTC, teekae commented on blinkstickcpp/include/blinkstick/device.hpp
> +#include <blinkstickcpp_export.h>
```suggestion
#include <blinkstick/export.hpp>
```

2019-12-19 13:45 UTC, DeveloperPaul123 commented
I've made the requested changes. Let me know if there's anything else!

2019-12-20 13:55 UTC, teekae approved these changes

2019-12-20 13:55 UTC, merged